### ISSUE TITLE
'rigid3d' is not recognized

### ISSUE THREAD

**Issue by nijiushi** [nicolaloi/Monocular-Visual-Odometry#1]
'rigid3d' is not recognized

**Comment by nicolaloi** [comment]
Hi, [rigid3d](https://www.mathworks.com/help/images/ref/rigid3d.html) is a function of the [Image Processing Toolbox](https://www.mathworks.com/help/images/index.html?s_tid=CRUX_lftnav), released with the Matlab version R2020a.
You should check your Matlab version and/or the presence of the toolbox.

**Comment by nijiushi** [comment]
Thanks a&nbsp; lot,Sir!


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "loinicola/Vision-Algorithms-for-Mobile-Robotics"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月23日(星期天) 晚上9:12
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [loinicola/Vision-Algorithms-for-Mobile-Robotics] 'rigid3d' is not recognized (Issue #1)





 
Hi, rigid3d is a function of the Image Processing Toolbox, released with the Matlab version R2020a.
 You should check your Matlab version and/or the presence of the toolbox.
